---
title: "02_data_viz"
author: Casey Breen
---

Summary: Read in some data, make some plots 

```{r}
## library packages 
library(tidyverse)
library(cowplot)
library(here)

## source a custom function from github for recoding education
source("https://raw.githubusercontent.com/caseybreen/censocdev/master/R/recode_education.R")
```


## three ways to read in data 

```{r}
## absolute path (with shortcut)
censoc <- read_csv("~/Downloads/censoc_numident_demo_v2.1.csv")

## relative path 
censoc <- read_csv("../../data/censoc_numident_demo_v2.1.csv")

## using here() package 
censoc <- read_csv(here("data", "censoc_numident_demo_v2.1.csv"))


censoc <- censoc %>% 
  recode_education(educ_var = "educd")
```


## data visualization 

There's 5 main plots I use over and over again in all of my papers. These are approximately 90% of the data visualizations I make. 


```{r}
## 1. Histogram 
histogram <- censoc %>% 
  ggplot(aes(x = death_age)) + 
  geom_histogram(color = "black", fill = "grey") + 
  theme_cowplot() + 
  labs(x = "Death Age", y = "Count")

histogram

## 2. Scatter plot 
scatter_plot <- censoc %>% 
  sample_n(1000) %>% 
  ggplot(aes(x = serial, y = death_age)) + 
  geom_point() + 
  geom_smooth() + 
  theme_cowplot() + 
  labs(x = "Serial", y = "Death Age")

scatter_plot
  
## 3. Column plot 
# prep data 
top_10_states <- censoc %>% 
  count(socstate_string) %>% 
  arrange(desc(n)) %>% 
  top_n(10)

# make plot 
column_plot <- top_10_states %>% 
  ggplot(aes(x = socstate_string, y = n)) + 
  geom_col(alpha = 0.6, fill = "darkred") + 
  geom_text(aes(label = n, y = 300)) + 
  theme_cowplot() +
  theme(axis.text.x = element_text(angle = -45, vjust = 0.5, hjust=0)) + 
  labs(x = "State", y = "Count")

column_plot

## 4. Dot plot (coefficient plot, if plotting reg coefficients)
# prep data 
avg_death_age_df <- censoc %>% 
  filter(socstate_string %in% top_10_states$socstate_string) %>% 
  group_by(socstate_string) %>% 
  summarize(death_age_avg = mean(death_age),
            death_age_std = sd(death_age)/sqrt(n()))

# make plot 
dot_plot <- avg_death_age_df %>% 
  ggplot(aes(y = reorder(socstate_string, death_age_avg), 
             x = death_age_avg,
             xmin = death_age_avg - 1.96 * death_age_std,
             xmax = death_age_avg + 1.96 * death_age_std)) + 
  geom_pointrange(shape = 21, fill = "white") + 
  theme_cowplot() +
  labs(x = "Death Age", y = "State")

dot_plot


## 5. Line plot
# prep data 
avg_edu_df <- censoc %>% 
  filter(byear %in% c(1900:1920)) %>% 
  group_by(byear) %>% 
  filter(!is.na(educ_yrs)) %>% 
  summarize(edu_attainment = mean(educ_yrs),
            edu_attainment_sd = sd(educ_yrs)/sqrt(n()))

# make plot 
line_plot <- avg_edu_df %>% 
  ggplot(aes(x = byear, y = edu_attainment, fill = byear)) + 
  geom_line() + 
  geom_point(size = 3, shape = 21) + 
  theme_cowplot() + 
  labs(x = "Birth Year", y = "Educational Attainment")

line_plot

  
```

```{r}
cowplot::plot_grid(histogram, scatter_plot, column_plot, dot_plot, line_plot, labels = "AUTO")
```

